name: Deploy dbt docs to GitHub Pages

on:
  push:
    branches:
      - main  # Runs on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install DBT & Snowflake Adapter
        run: |
          pip install dbt-core dbt-snowflake

      - name: Configure DBT Profiles
        run: |
          mkdir -p ~/.dbt
          echo "${{ secrets.DBT_PROFILES }}" > ~/.dbt/profiles.yml

      - name: Install DBT Dependencies
        run: dbt deps

      - name: Generate DBT Docs
        run: dbt docs generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./target  # The folder where dbt docs are generated
